### ISSUE TITLE
two fixes needed for installation on MacOS 10.13.6 with python3.7

### ISSUE THREAD

**Issue by vdhulst** [commontk/qt-easy-build#59]
I needed Qt5 to build Slicer and SlicerAstroApp and used this distribution as other installations failed. When building and installing Qt5 I ran into two errors I needed to fix. The messages and fixes I made are given below.

_**error 1:**_

```
ninja  -C /Users/vdhulst/Software/qt-everywhere-src-5.15.0/qtwebengine/src/core/release QtWebEngineCore
ninja: Entering directory `/Users/vdhulst/Software/qt-everywhere-src-5.15.0/qtwebengine/src/core/release'
[1/15903] LIBTOOL-STATIC obj/third_party/SPIRV-Tools/src/libspvtools.a
FAILED: obj/third_party/SPIRV-Tools/src/libspvtools.a 
rm -f obj/third_party/SPIRV-Tools/src/libspvtools.a && TOOL_VERSION=1588774889 python ../../3rdparty/chromium/build/toolchain/mac/filter_libtool.py /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static  -o obj/third_party/SPIRV-Tools/src/libspvtools.a -filelist obj/third_party/SPIRV-Tools/src/libspvtools.a.rsp
Traceback (most recent call last):
  File "../../3rdparty/chromium/build/toolchain/mac/filter_libtool.py", line 56, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "../../3rdparty/chromium/build/toolchain/mac/filter_libtool.py", line 43, in Main
    if not IsBlacklistedLine(line):
  File "../../3rdparty/chromium/build/toolchain/mac/filter_libtool.py", line 28, in IsBlacklistedLine
    if pattern.match(line):
TypeError: cannot use a string pattern on a bytes-like object
[10/15903] CXX obj/third_party/SPIRV-Tools/src/spvtools_opt/amd_ext_to_khr.o
ninja: build stopped: subcommand failed.
make[4]: *** [run_ninja] Error 1
make[3]: *** [sub-gn_run-pro-make_first] Error 2
make[2]: *** [sub-core-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2
```

fixed by changing: `if pattern.match(line):` into `if pattern.match(str(line)):`
in filter_libtool.py

**_error 2:_**

```
In file included from gen/third_party/blink/renderer/core/core_generated_jumbo_11.cc:8:
/Users/vdhulst/Software/qt-everywhere-src-5.15.0/qtwebengine/src/core/release/gen/third_party/blink/renderer/core/xpath_grammar.cc:124:10: fatal error: 'xpath_grammar.hh' file not found
#include "xpath_grammar.hh"
```

 fixed by changing `#include "xpath_grammar.hh"` into `#include "xpath_grammar.h"`
 in xpath_grammar.cc

**Comment by jcfr** [comment]
Thanks for the report :pray: 

Could you confirm you built of this branch https://github.com/jcfr/qt-easy-build/tree/5.15.0 ? 

@jamesobutler  Are you familiar with these ?

**Comment by vdhulst** [comment]
Yes I did build the 5.15.0 Qt branch.

**Comment by jcfr** [comment]
Closing. Build system was updated in https://github.com/jcfr/qt-easy-build/commit/ea3b43d2d17a51e2e4fc7196e8eee7ef48798108 to build Python 2.7:
* #69
